#!/bin/bash

# Set up custom builder
# docker buildx create --name mycustombuilder --driver docker-container --platform linux/amd64,linux/arm64 --bootstrap
# docker buildx use mycustombuilder
# docker buildx inspect

# Use cloud builder
docker buildx create --driver cloud intellicon/multiarch

# Build for multiple platforms
# docker buildx build --push --platform linux/amd64,linux/arm64 -t $IMAGE_NAME .
docker buildx build --builder cloud-intellicon-multiarch --platform linux/amd64,linux/arm64 --tag IMAGE --push .
