#!/bin/bash

# Set up custom builder
docker buildx create --name mycustombuilder --driver docker-container --platform linux/amd64,linux/arm64 --bootstrap
docker buildx use mycustombuilder
docker buildx inspect

# What are we building?
echo "Tag: $IMAGE_NAME"

# Build for multiple platforms
docker buildx build --push --platform linux/amd64,linux/arm64 -t $IMAGE_NAME .
