#!/bin/bash

# Set up custom builder
docker buildx create --name mycustombuilder --driver docker-container --bootstrap
docker buildx use mycustombuilder
docker buildx inspect

# Build for multiple platforms
docker buildx build --platform linux/amd64,linux/arm64 -t $IMAGE_NAME .
